### ISSUE TITLE
Add commands for common links

### ISSUE THREAD

**Issue by namanyt** [Carberra/tutorials-twitch-bot#14]
just a `+plans` command same as your discord bot `+plans` command :)

**Comment by Olivier-Berg** [comment]
<img width="166" alt="Schermafbeelding 2021-05-15 om 17 55 21" src="https://user-images.githubusercontent.com/73174454/118370164-c0df7280-b5a6-11eb-8c03-1d7c237a93fb.png">
prolly all these links except pep and google

**Comment by mshaugh** [comment]
Should implement commands for all links as mentioned by @IkBenOlie5:

- [ ] discord
- [ ] docs
- [ ] donate
- [ ] facebook
- [ ] github
- [ ] odysee (formerly lbry)
- [ ] patreon
- [ ] plans
- [ ] twitter
- [ ] youtube

**Comment by IkBenOlie5** [comment]
twitch prolly not lmao

**Comment by namanyt** [comment]
what is the `pep` link ?

**Comment by Olivier-Berg** [comment]
it gives you a link to a certain pep

**Comment by mshaugh** [comment]
https://github.com/Carberra/Carberretta/blob/master/carberretta/bot/cogs/links.py
